enablePlugins(SbtWeb)

val js = project

scalaVersion in ThisBuild := "2.11.7"

val scalaJsFiles = taskKey[Seq[File]]("JavaScript files generated by Scala.js")

scalaJsFiles := {
  val jsFile = (fastOptJS in js in Compile).value.data
  val destinationFile = (sourceManaged in Assets).value / jsFile.getName
  IO.copyFile(jsFile, destinationFile)
  Seq(destinationFile)
}

resourceGenerators in Assets <+= scalaJsFiles

resourceGenerators in Assets <+= Def.task[Seq[File]] {
  val jsFile = (fastOptJS in js in Compile).value.data
  val mapFile = jsFile.getParentFile / s"${jsFile.getName}.map"
  val destinationFile = (sourceManaged in Assets).value / mapFile.getName
  IO.copyFile(mapFile, destinationFile)
  Seq(destinationFile)
}

resourceGenerators in Assets <+= Def.task[Seq[File]] {
  val base = (sourceManaged in Assets).value
  val indexHtml = base / "index.html"
  IO.writeLines(
    indexHtml,
    Seq(
      "<!DOCTYPE html>",
      xml.Xhtml.toXhtml(<html>
        <head>
          {for {
          jsFile <- scalaJsFiles.value
        } yield {
          <script type="text/javascript" src={jsFile.getName}></script>
        }}
        </head>
        <body>
          <script type="text/javascript">
            SampleMain().main()
          </script>
        </body>
      </html>)))
  Seq(indexHtml)
}